version: '3'
services:
  tests:
    image: pytest_api
    command: ./execute_tests.sh
    depends_on:
      - setup
    volumes:
      - .:/app
    environment:
      - DOCKER_RUN=True
  setup:
    build:
      context: .
      dockerfile: Dockerfile
    image: pytest_api